# Understanding the multiple comparisons problem {#ch:MultComp} 


```{r}
library(knitr)
library(kableExtra)
library(tidyverse)
library(brms)
library(bcogsci)
library(papaja)
library(afex)
library(MASS)
library(hypr)
```

# Introduction

## Example: a two-condition repeated measures design

## Example: a $2\times 2$

## Example: a $2\times 2 \times 2$ repeated measures design

```{r}
library(lingpsych)
data("dillonE1ttnested")
library(brms)
postD_mE1ttnested<-posterior_samples(dillonE1ttnested)
beta1<-postD_mE1ttnested$b_Intercept
beta2<-postD_mE1ttnested$"b_dep"
beta3<-postD_mE1ttnested$"b_gram"
beta4<-postD_mE1ttnested$"b_dep:gram"
beta5<-postD_mE1ttnested$"b_int.rg"
beta6<-postD_mE1ttnested$"b_int.ag"
## the two estimates of interest:
beta7<-postD_mE1ttnested$"b_int.ru"
beta8<-postD_mE1ttnested$"b_int.au"

cor<-posterior_samples(postD_mE1ttnested,"^cor")
sd<-posterior_samples(postD_mE1ttnested,"^sd")
sigma<-posterior_samples(postD_mE1ttnested,"sigma")

item_re<-posterior_samples(postD_mE1ttnested,"^r_item")
subj_re<-posterior_samples(postD_mE1ttnested,"^r_subj")

library(SIN)
sds<-colMeans(sd)
cors<-colMeans(cor)
sig<-mean(sigma$sigma)
## assume 0 correlation as in models:
cormat<-matrix(rep(0,8*8),ncol=8)
diagmat<-diag(rep(1,8))
cormat<-cormat+diagmat
Sigma_u<-SIN::sdcor2cov(stddev=sds[8+(c(1,2,3,8,7,5,6,4))],
                          corr=cormat)
Sigma_w<-SIN::sdcor2cov(stddev=sds[c(1,2,3,8,7,5,6,4)],
                          corr=cormat)
```

```{r}
library(MASS)
## assumes that no. of subjects and no. of items is divisible by 8.
gen_fake_lnorm2x2x2<-function(ncond=8,
                              nitem=NULL,
                              nsubj=NULL,
                              beta=NULL,
                              Sigma_u=NULL, # subject vcov matrix
                              Sigma_w=NULL, # item vcov matrix
                              sigma_e=NULL){
  grouping<-matrix(rep(NA,ncond*ncond),ncol=ncond)
  grouping[1,]<-1:8
  grouping[2,]<-c(2:8,1)
  grouping[3,]<-c(3:8,1:2)
  grouping[4,]<-c(4:8,1:3)
  grouping[5,]<-c(5:8,1:4)
  grouping[6,]<-c(6:8,1:5)
  grouping[7,]<-c(7:8,1:6)
  grouping[8,]<-c(8,1:7)

  ## prepare data frame for 8 condition latin square:
  g1<-data.frame(item=1:nitem,
                 cond=rep(grouping[1,],nitem/ncond))
  g2<-data.frame(item=1:nitem,
                 cond=rep(grouping[2,],nitem/ncond))
  g3<-data.frame(item=1:nitem,
                 cond=rep(grouping[3,],nitem/ncond))
  g4<-data.frame(item=1:nitem,
                 cond=rep(grouping[4,],nitem/ncond))
  g5<-data.frame(item=1:nitem,
                 cond=rep(grouping[5,],nitem/ncond))
  g6<-data.frame(item=1:nitem,
                 cond=rep(grouping[6,],nitem/ncond))
  g7<-data.frame(item=1:nitem,
                 cond=rep(grouping[7,],nitem/ncond))
  g8<-data.frame(item=1:nitem,
                 cond=rep(grouping[8,],nitem/ncond))


  ## assemble data frame:
  gp1<-g1[rep(seq_len(nrow(g1)),
              nsubj/ncond),]
  gp2<-g2[rep(seq_len(nrow(g2)),
              nsubj/ncond),]
  gp3<-g3[rep(seq_len(nrow(g3)),
              nsubj/ncond),]
  gp4<-g4[rep(seq_len(nrow(g4)),
              nsubj/ncond),]
  gp5<-g5[rep(seq_len(nrow(g5)),
              nsubj/ncond),]
  gp6<-g6[rep(seq_len(nrow(g6)),
              nsubj/ncond),]
  gp7<-g7[rep(seq_len(nrow(g7)),
              nsubj/ncond),]
  gp8<-g8[rep(seq_len(nrow(g8)),
              nsubj/ncond),]

  fakedat<-rbind(gp1,gp2,gp3,gp4,gp5,gp6,gp7,gp8)

  ## add subjects:
  fakedat$subj<-rep(1:nsubj,each=nitem)

  ## add contrast coding:
  fakedat$Dep <- ifelse(fakedat$cond %in% c(1:4), 1, -1) # main effect of dependency type: agr=1, refl=-1
  fakedat$Gram <- ifelse(fakedat$cond %in% c(1,2,5,6), -1, 1) # main effect of grammaticality: gram=-1, ungram=1
  fakedat$DepxGram <- ifelse(fakedat$cond %in% c(3:6), 1, -1)
  fakedat$Int_gram_refl <- ifelse(fakedat$cond %in% c(5), 1, ifelse  (fakedat$cond %in% c(6), -1, 0))
  fakedat$Int_gram_agr <- ifelse(fakedat$cond %in% c(1), 1, ifelse(fakedat$cond %in% c(2), -1, 0))
  fakedat$Int_ungram_refl <- ifelse(fakedat$cond %in% c(8), 1, ifelse(fakedat$cond %in% c(7), -1, 0))
  fakedat$Int_ungram_agr <- ifelse(fakedat$cond %in% c(4), 1, ifelse(fakedat$cond %in% c(3), -1, 0))
  ## subject random effects:
  u<-mvrnorm(n=length(unique(fakedat$subj)),
             mu=c(rep(0,8)),Sigma=Sigma_u)

  ## item random effects
  w<-mvrnorm(n=length(unique(fakedat$item)),
             mu=c(rep(0,8)),Sigma=Sigma_w)

  ## generate data row by row:
  N<-dim(fakedat)[1]
  rt<-rep(NA,N)
  for(i in 1:N){
    rt[i] <- rlnorm(1,beta[1] +
                      u[fakedat[i,]$subj,1] +
                      w[fakedat[i,]$item,1] +
                      (beta[2]+u[fakedat[i,]$subj,2]+
                         w[fakedat[i,]$item,2])*fakedat$Dep[i]+
                      (beta[3]+u[fakedat[i,]$subj,3]+
                         w[fakedat[i,]$item,3])*fakedat$Gram[i]+
                      (beta[4]+u[fakedat[i,]$subj,4]+
                         w[fakedat[i,]$item,4])*fakedat$DepxGram[i]+
                      (beta[5]+u[fakedat[i,]$subj,5]+
                         w[fakedat[i,]$item,5])*fakedat$Int_gram_refl[i]+
                      (beta[6]+u[fakedat[i,]$subj,6]+
                         w[fakedat[i,]$item,6])*fakedat$Int_gram_agr[i]+
                      (beta[7]+u[fakedat[i,]$subj,7]+
                         w[fakedat[i,]$item,7])*fakedat$Int_ungram_refl[i]+
                      (beta[8]+u[fakedat[i,]$subj,8]+
                         w[fakedat[i,]$item,8])*fakedat$Int_ungram_agr[i],

                    sigma_e)
  }
  fakedat$rt<-rt
  fakedat$subj<-factor(fakedat$subj)
  fakedat$item<-factor(fakedat$item)
  fakedat
}

## set all effects to 0:
betameans[2:8]<-0

nsim<-100
significant<-matrix(0,nsim,ncol=7)
## record failed convergences, remove these later:
failed<-rep(0,nsim)

for(i in 1:nsim){
    print(paste("********simulation ",i,"********",sep=""))
  fakedat<-gen_fake_lnorm2x2x2(beta = betameans,
                               Sigma_u=Sigma_u,Sigma_w=Sigma_w,
                               sigma_e=sig,nitem=48,
                               nsubj=40)

  m_fake<-lmer(log(rt)~Dep+Gram+DepxGram+Int_gram_refl+Int_gram_agr+
                 Int_ungram_refl+Int_ungram_agr+
                 (1|subj)+
                 (1|item),fakedat,
               control=lmerControl(optimizer="nloptwrap", calc.derivs = FALSE))

  ## ignore failed trials
##  if(any( grepl("failed to converge", m_fake@optinfo$conv$lme4$messages) ) ||
##     any( grepl("singular", m_fake@optinfo$conv$lme4$messages) )){
##    failed[i]<-1
##  } else{
    ## first slope:
    if(abs(summary(m_fake)$coefficients[2,3])>2){
      significant[i,1]<-1
    } else {significant[i,1]<-0}
    ## second slope:
    if(abs(summary(m_fake)$coefficients[3,3])>2){
      significant[i,2]<-1
    } else {significant[i,2]<-0}
    ## third slope:
    if(abs(summary(m_fake)$coefficients[4,3])>2){
      significant[i,3]<-1
    } else {significant[i,3]<-0}
    ## fourth slope:
    if(abs(summary(m_fake)$coefficients[5,3])>2){
      significant[i,4]<-1
    } else {significant[i,4]<-0}
    ## fifth slope:
    if(abs(summary(m_fake)$coefficients[6,3])>2){
      significant[i,5]<-1
    } else {significant[i,5]<-0}
    ## sixth slope:
    if(abs(summary(m_fake)$coefficients[7,3])>2){
      significant[i,6]<-1
    } else {significant[i,6]<-0}
    ## seventh slope:
    if(abs(summary(m_fake)$coefficients[8,3])>2){
      significant[i,7]<-1
    } else {significant[i,7]<-0}
    ##}
}

## In 100 simulations, what is the proportion of times that *at least one* of the effects is significant?
## save results:
save(significant,file="minimalmodelsig.rda")

counts<-table(rowSums(significant)>0)
counts[2]/sum(counts)
## Type I error under multiple comparisons.

colSums(significant)/100


## full model:
nsim<-100
significant<-matrix(0,nsim,ncol=7)
## record failed convergences, remove these later:
failed<-rep(0,nsim)

for(i in 1:nsim){
  print(paste("********simulation ",i,"********",sep=""))
  fakedat<-gen_fake_lnorm2x2x2(beta = betameans,
                               Sigma_u=Sigma_u,Sigma_w=Sigma_w,
                               sigma_e=sig,nitem=48,
                               nsubj=40)

  m_fake<-lmer(log(rt)~Dep+Gram+DepxGram+Int_gram_refl+Int_gram_agr+
                 Int_ungram_refl+Int_ungram_agr+
                 (1+Dep+Gram+DepxGram+Int_gram_refl+Int_gram_agr+
                    Int_ungram_refl+Int_ungram_agr||subj)+
                 (1|item),fakedat,
               control=lmerControl(optimizer="nloptwrap", calc.derivs = FALSE))

  ## ignore failed trials
    if(any( grepl("failed to converge", m_fake@optinfo$conv$lme4$messages) ) ||
       any( grepl("singular", m_fake@optinfo$conv$lme4$messages) )){
      failed[i]<-1
    } else{
  ## first slope:
  if(abs(summary(m_fake)$coefficients[2,3])>2){
    significant[i,1]<-1
  } else {significant[i,1]<-0}
  ## second slope:
  if(abs(summary(m_fake)$coefficients[3,3])>2){
    significant[i,2]<-1
  } else {significant[i,2]<-0}
  ## third slope:
  if(abs(summary(m_fake)$coefficients[4,3])>2){
    significant[i,3]<-1
  } else {significant[i,3]<-0}
  ## fourth slope:
  if(abs(summary(m_fake)$coefficients[5,3])>2){
    significant[i,4]<-1
  } else {significant[i,4]<-0}
  ## fifth slope:
  if(abs(summary(m_fake)$coefficients[6,3])>2){
    significant[i,5]<-1
  } else {significant[i,5]<-0}
  ## sixth slope:
  if(abs(summary(m_fake)$coefficients[7,3])>2){
    significant[i,6]<-1
  } else {significant[i,6]<-0}
  ## seventh slope:
  if(abs(summary(m_fake)$coefficients[8,3])>2){
    significant[i,7]<-1
  } else {significant[i,7]<-0}
  }
}

## In 100 simulations, what is the proportion of times that *at least one* of the effects is significant?
save(significant,file="maxmodelsig.rda")
counts<-table(rowSums(significant)>0)
counts[2]/sum(counts)
## Type I error under multiple comparisons.

colSums(significant)/100

## full model 2:
nsim<-100
significant<-matrix(0,nsim,ncol=7)
## record failed convergences, remove these later:
failed<-rep(0,nsim)

for(i in 1:nsim){
  print(paste("********simulation ",i,"********",sep=""))
  fakedat<-gen_fake_lnorm2x2x2(beta = betameans,
                               Sigma_u=Sigma_u,Sigma_w=Sigma_w,
                               sigma_e=sig,nitem=48,
                               nsubj=40)

  m_fake<-lmer(log(rt)~Dep+Gram+DepxGram+Int_gram_refl+Int_gram_agr+
                 Int_ungram_refl+Int_ungram_agr+
                 (1+Dep+Gram+DepxGram+Int_gram_refl+Int_gram_agr+
                    Int_ungram_refl+Int_ungram_agr||subj)+
                 (1+Dep+Gram+DepxGram+Int_gram_refl+Int_gram_agr+
                    Int_ungram_refl+Int_ungram_agr||item),fakedat,
               control=lmerControl(optimizer="nloptwrap", calc.derivs = FALSE))

  ## ignore failed trials
  if(any( grepl("failed to converge", m_fake@optinfo$conv$lme4$messages) ) ||
     any( grepl("singular", m_fake@optinfo$conv$lme4$messages) )){
    failed[i]<-1
  } else{
    ## first slope:
    if(abs(summary(m_fake)$coefficients[2,3])>2){
      significant[i,1]<-1
    } else {significant[i,1]<-0}
    ## second slope:
    if(abs(summary(m_fake)$coefficients[3,3])>2){
      significant[i,2]<-1
    } else {significant[i,2]<-0}
    ## third slope:
    if(abs(summary(m_fake)$coefficients[4,3])>2){
      significant[i,3]<-1
    } else {significant[i,3]<-0}
    ## fourth slope:
    if(abs(summary(m_fake)$coefficients[5,3])>2){
      significant[i,4]<-1
    } else {significant[i,4]<-0}
    ## fifth slope:
    if(abs(summary(m_fake)$coefficients[6,3])>2){
      significant[i,5]<-1
    } else {significant[i,5]<-0}
    ## sixth slope:
    if(abs(summary(m_fake)$coefficients[7,3])>2){
      significant[i,6]<-1
    } else {significant[i,6]<-0}
    ## seventh slope:
    if(abs(summary(m_fake)$coefficients[8,3])>2){
      significant[i,7]<-1
    } else {significant[i,7]<-0}
  }
}

## In 100 simulations, what is the proportion of times that *at least one* of the effects is significant?
save(significant,file="maxmodelsig2.rda")
counts<-table(rowSums(significant)>0)
counts[2]/sum(counts)
## Type I error under multiple comparisons.

colSums(significant)/100

```
